defaults:
  - defaults

name: indice
code_dim: 512
nb_code: 512
motion_type: mano
contact_grid: 16
contact_dim: 16
video_feats: 768
text_feats: true
pred_cam: true
contact_map: true
return_indices: true
setting: tasks